### PR TITLE
linux path updated

### PR DESCRIPTION
**Pull request by puncoz**
LINUX_PATH issue fixed for linux machine.

image

### CODE REVIEW

**Comment by mallowigi** [comment]
Does this work for all Slack envs? I recall having a lot of issues when installing from the Ubuntu store

**Comment by puncoz** [comment]
I tested it in Arch Linux, for both slack official installation as well as installation from Arch User Repository (AUR). And it works. I think the newer version of slack changed path making it similar to Mac OS and Windows.

**Comment by nomad-mystic** [comment]
Yeah having an issue with installing when I have a SNAP version of slack. 
Ubuntu 18.4.0 
NVM 10.16.3 and 12.6.0 used 
Both sudo and not sudo. 
`slack-themes on  master is 📦 v1.0.0 via ⬢ v10.16.3 
➜ sudo npm install    
[ .................] / loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> node-sass@4.12.0 install /home/keith/Packages/slack-themes/node_modules/node-sass
> node scripts/install.js

Unable to save binary /home/keith/Packages/slack-themes/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/home/keith/Packages/slack-themes/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/home/keith/Packages/slack-themes/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/home/keith/Packages/slack-themes/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/home/keith/Packages/slack-themes/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/home/keith/Packages/slack-themes/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/home/keith/Packages/slack-themes/node_modules/node-sass/vendor' }
`

**Comment by nomad-mystic** [comment]
Getting this on apply theme on Ubuntu 18.04.0
Slack installed with SANP -> $HOME/snap/slack 
Node version 10.16.3
run with sudo and not sudo

`Select a theme Material Palenight
Selected: palenight
current theme is now Material Palenight
Adding Material Palenight Theme Code to Slack... 

(node:27173) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile '/usr/lib/slack/resources/app.asar' -> '/usr/lib/slack/resources/app.asar.backup'
    at Object.copyFileSync (fs.js:1728:3)
    at Object.exports.apply (/home/keith/Packages/slack-themes/lib/command.js:65:6)
    at Object.exports.selectTheme (/home/keith/Packages/slack-themes/lib/command.js:97:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27173) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Pull request closed without merging**
